### ISSUE TITLE
Install does not work

### ISSUE THREAD

**Issue by KristianHeider** [ioBroker/ioBroker.cameras#17]
**Describe the bug**  
Installation takes really long (around 10min) and after no error is shown there is no instances. I tried it on docker and raspberry 

**To Reproduce**  
I tried all way:
1. install from github
2. install from npm
3. install in terminal with npm

**Expected behavior**  
Instance is created and configurable.
With "iobroker list instances" there is no cameras at all

**Screenshots & Logfiles**  
This is terminal log:
```
pi@homematicRasp:/opt/iobroker $ npm install iobroker.cameras
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ iobroker.cameras@0.1.8
updated 1 package in 828.737s
```

**Versions:**  
iobroker 4.0.23
admin 5.3.8

**Additional context**  
Please ask for further informations

**Comment by KristianHeider** [comment]
Sorry myself: if you do not add instances there can not be any.

**Comment by Apollon77** [comment]
Also, WHY you install it that way? Please use Admin or the iobroker cli commands because that way you also need to run "iob upload cameras" .. so best please do it the official ways and not strange direct workarounds
