### ISSUE TITLE
implement foscam 

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.cameras#4]
foscam send a pic from address

http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=usr&pwd=psw

its a jpg

**Comment by Brainbug01** [comment]
I think it works when you use this link without any implementation?
My URL is this: http://ip/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=xxxxxxxxxxxx&user=user&password=password and it works.

**Comment by Brainbug01** [comment]
Do you test this URLs:
https://www.ispyconnect.com/man.aspx?n=foscam
