### ISSUE TITLE
Fehler Adapter and Instar integration

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.cameras#5]
Moin,

Instar hat folgende URL zum requesten eines Bildes: 
Methode 1: http://IP/tmpfs/snap.jpg?usr=Username&pwd=Password
Methode 2: http://User:Password@192.168.2.105/tmpfs/snap.jpg

Und hier einen Link falls man etwas anderes als JPG benötigt: https://wiki.instar.de/1080p_Serie_CGI_Befehle/

Links: https://wiki.instar.de/Software/Smarthome/IOBroker/

Nun kommen wir zu den Fehlern die ich habe:

Wenn ich den Adapter mit Listen on all IP starte startet er ohne fehler (bleibt aber grau) und wenn ich die ip aufrufe kommt entweder Invalid key oder Blocked for 5 seconds. In den Cam einstellungen bekomme ich ein Bild angezeigt die dort eingetragene url sollte also gehen.

Wenn ich den Adapter mit der Webinstance konfigure und starte kommen folgende Fehlermeldungen: 

`

host.ioBroker | 2020-05-30 14:09:05.288 | info | Restart adapter system.adapter.cameras.0 because enabled
-- | -- | -- | --
host.ioBroker | 2020-05-30 14:09:05.288 | info | instance system.adapter.cameras.0 terminated with code 0 (NO_ERROR)
cameras.0 | 2020-05-30 14:09:04.718 | info | (2122) Terminated (NO_ERROR): Without reason
cameras.0 | 2020-05-30 14:09:04.717 | info | (2122) terminating
cameras.0 | 2020-05-30 14:09:04.665 | error | (2122) Error: getaddrinfo ENOTFOUND * at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
cameras.0 | 2020-05-30 14:09:04.664 | error | (2122) uncaught exception: getaddrinfo ENOTFOUND *
cameras.0 | 2020-05-30 14:09:04.154 | debug | (2122) Request {"url":"http://IP/tmpfs/snap.jpg?usr=Username&pwd=Password","name":"Treppenhaus","type":"url","id":1590839514422,"path":"/Treppenhaus"}
cameras.0 | 2020-05-30 14:09:04.146 | debug | (2122) Request {"url":"http://IP/tmpfs/snap.jpg?usr=Username&pwd=Password","name":"Hof","desc":"Cam Hof","type":"url","id":1590839508661,"path":"/Hof"}
cameras.0 | 2020-05-30 14:09:03.811 | info | (2122) starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.cameras, node: v12.16.2, js-controller: 3.1.4
host.ioBroker | 2020-05-30 14:09:02.341 | info | instance system.adapter.cameras.0 started with pid 2122
host.ioBroker | 2020-05-30 14:08:32.283 | info | Restart adapter system.adapter.cameras.0 because enabled
host.ioBroker | 2020-05-30 14:08:32.282 | info | instance system.adapter.cameras.0 terminated with code 0 (NO_ERROR)
cameras.0 | 2020-05-30 14:08:31.241 | info | (2049) Terminated (NO_ERROR): Without reason
cameras.0 | 2020-05-30 14:08:31.241 | info | (2049) terminating
cameras.0 | 2020-05-30 14:08:31.195 | error | at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
cameras.0 | 2020-05-30 14:08:31.195 | error | (2049) Error: getaddrinfo ENOTFOUND *
cameras.0 | 2020-05-30 14:08:31.194 | error | (2049) uncaught exception: getaddrinfo ENOTFOUND *
cameras.0 | 2020-05-30 14:08:30.893 | debug | (2049) Request {"url":"http://IP/tmpfs/snap.jpg?usr=Username&pwd=Password","name":"Treppenhaus","type":"url","id":1590839514422,"path":"/Treppenhaus"}
cameras.0 | 2020-05-30 14:08:30.889 | debug | (2049) Request {"url":"http://IP/tmpfs/snap.jpg?usr=Username&pwd=Password","name":"Hof","desc":"Cam Hof","type":"url","id":1590839508661,"path":"/Hof"}
cameras.0 | 2020-05-30 14:08:30.710 | info | (2049) starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.cameras, node: v12.16.2, js-controller: 3.1.4
cameras.0 | 2020-05-30 14:08:30.077 | debug | (2049) statesDB connected
cameras.0 | 2020-05-30 14:08:30.076 | debug | (2049) States connected to redis: 0.0.0.0:9000
cameras.0 | 2020-05-30 14:08:30.064 | debug | (2049) States create System PubSub Client
cameras.0 | 2020-05-30 14:08:30.062 | debug | (2049) States create User PubSub Client
cameras.0 | 2020-05-30 14:08:30.055 | debug | (2049) Redis States: Use Redis connection: 0.0.0.0:9000
cameras.0 | 2020-05-30 14:08:30.054 | debug | (2049) objectDB connected
cameras.0 | 2020-05-30 14:08:30.051 | debug | (2049) Objects connected to redis: 0.0.0.0:9001
cameras.0 | 2020-05-30 14:08:30.035 | debug | (2049) Objects client initialize lua scripts
cameras.0 | 2020-05-30 14:08:30.035 | debug | (2049) Objects create User PubSub Client
cameras.0 | 2020-05-30 14:08:30.034 | debug | (2049) Objects create System PubSub Client
cameras.0 | 2020-05-30 14:08:30.021 | debug | (2049) Objects client ready ... initialize now
cameras.0 | 2020-05-30 14:08:29.997 | debug | (2049) Redis Objects: Use Redis connection: 0.0.0.0:9001
host.ioBroker | 2020-05-30 14:08:29.679 | info | instance system.adapter.cameras.0 started with pid 2049

`

**Comment by Brainbug01** [comment]
Der Adapter ist bei mir auch Grau aber trotzdem bekomme ich Bilder. Eingestellt habe ich: Listen on all IPs. Eingetragen sind bei mir 3 Kameras, eine mit basic auth und zwei ohne. Die URL eintragen und speichern und dann speichern und schließen. Danach nochmal auf den Stift und dann konnte ich per Web URL das Bild ansehen.

**Comment by vr6syncro** [comment]
Geht tatsächlich.

Was auch noch wünschenswert wäre ist der mjpeg support das geht noch nicht.

z.B.
http://IP/tmpfs/mjpegstream.cgi?-chn=11?usr=User&pwd=Password

**Comment by Brainbug01** [comment]
Ich bin mir nicht sicher ob der Adapter für einen Stream ausgelegt sein soll oder nur für das einzelne Bild.

Der Adapter ist jedenfalls RAM hungrig, 700mb bei drei Kameras.
