### ISSUE TITLE
Neue Kamera anlegen 

### ISSUE THREAD

**Issue by arniworx** [ioBroker/ioBroker.cameras#66]
hi!
nach aktualisierung auf version v1.0.2 des camera adapters, kann ich keine kameras vom typ "URL with basic auth" und keine "RTSP-Snapshot" kamera anlegen. wenn man eingaben (ip, pfad, etc:) machen möchte, springt der dialog auf den standard typ "URL" zurück. nur in die felder "Cache Timeout" und "Add Title" kann man etwas eintragen. wäre schön, wenn sich das mal jemand angucken könnte.
danke.

Browser getestet: Edge/Chrome/Waterfox
Platform: Ubuntu 22.04.1
Admin: v6.3.5
Node.js: v16.19.0
NPM: 8.19.3

**Comment by xmace** [comment]
+1

**Comment by Apollon77** [comment]
Thumbs us is the better +1 @xmace

**Comment by arniworx** [comment]
ok, in der v1.0.3 funktioniert die eingabe. danke dafür.
etwas irreführend ist allerdings der beispieleintrag "rtsp://admin:***@:554" beim eingabefeld "Path". 
und es wäre schön eine camera mit namen anlegen zu können anstelle einer IP.
sonst habe ich nichts zu meckern ;-)
thx
